### ISSUE TITLE
Angular CLI Compiler Warning

### ISSUE THREAD

**Issue by kevinaud** [kevinaud/ng-aws-cognito-project#13]
We get this compiler warning every time the app builds. It doesn't cause any issues as far as I can tell, but it would be nice if we could figure out how to get rid of it. We don't want a developer's first impression of our library to be a compiler warning.

WARNING in ./~/raw-loader!./~/source-map-loader!./src/scripts/apiGateway-js-sdk/lib/axios/dist/axios.standalone.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'axios.map': Error: Can't resolve './axios.map' in '/home/kevinaud/bin/ng-aws-cognito-project/src/scripts/apiGateway-js-sdk/lib/axios/dist'
 @ ./~/script-loader!./src/scripts/apiGateway-js-sdk/lib/axios/dist/axios.standalone.js 1:95-371
 @ multi script-loader!./src/scripts/apiGateway-js-sdk/lib/axios/dist/axios.standalone.js script-loader!./src/scripts/apiGateway-js-sdk/lib/CryptoJS/rollups/hmac-sha256.js script-loader!./src/scripts/apiGateway-js-sdk/lib/CryptoJS/rollups/sha256.js script-loader!./src/scripts/apiGateway-js-sdk/lib/CryptoJS/components/hmac.js script-loader!./src/scripts/apiGateway-js-sdk/lib/CryptoJS/components/enc-base64.js script-loader!./src/scripts/apiGateway-js-sdk/lib/url-template/url-template.js script-loader!./src/scripts/apiGateway-js-sdk/lib/apiGatewayCore/sigV4Client.js script-loader!./src/scripts/apiGateway-js-sdk/lib/apiGatewayCore/apiGatewayClient.js script-loader!./src/scripts/apiGateway-js-sdk/lib/apiGatewayCore/simpleHttpClient.js script-loader!./src/scripts/apiGateway-js-sdk/lib/apiGatewayCore/utils.js script-loader!./src/scripts/apiGateway-js-sdk/apigClient.js

**Comment by moshejs** [comment]
by removing

//# sourceMappingURL=axios.map

from './src/scripts/apiGateway-js-sdk/lib/axios/dist/axios.standalone.js' the error is completely gone.
Since no sourcemap is provided (and for good reason - doesn't seem like it will not be supported), it is safe to remove this from the library. Added this to my commit history
